# Generated by Django 2.2.10 on 2020-10-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_auto_20201026_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_date',
        ),
    ]
