# Generated by Django 2.2.10 on 2020-10-26 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_remove_picture_picture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
