# Generated by Django 2.2.10 on 2020-10-27 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artgallery', '0007_picture_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(related_name='artpieces', to=settings.AUTH_USER_MODEL),
        ),
    ]
