# Generated by Django 2.2.10 on 2020-10-27 19:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0008_picture_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
