# Generated by Django 2.2.10 on 2020-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0009_auto_20201027_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
