# Generated by Django 2.2.10 on 2020-10-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201028_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
