# Generated by Django 2.2.10 on 2020-11-08 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_done',
            field=models.ManyToManyField(blank='True', related_name='is_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
