# Generated by Django 2.2.10 on 2020-11-09 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_done',
            field=models.ManyToManyField(blank=True, related_name='is_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
