# Generated by Django 2.2.10 on 2020-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201109_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
